export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const GET_USERS_REQUEST = 'GET_USERS_REQUEST';
export const GET_USERS_FAIL = 'GET_USERS_FAIL';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';

export const GET_USER_REQUEST = 'GET_USER_REQUEST';
export const GET_USER_FAIL = 'GET_USER_FAIL';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';

export const SIGNIN_REQUEST = 'SIGNIN_REQUEST';
export const SIGNIN_FAIL = 'SIGNIN_FAIL';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';

export const REQUEST_REQUEST = 'REQUEST_REQUEST';
export const REQUEST_FAIL = 'REQUEST_FAIL';
export const REQUEST_SUCCESS = 'REQUEST_SUCCESS';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const LOGOUT = 'LOGOUT';

export const FORGOT_PASSWORD_REQUEST = 'FORGOT_PASSWORD_REQUEST';
export const FORGOT_PASSWORD_FAIL = 'FORGOT_PASSWORD_FAIL';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';

export const CONFIRM_OTP_REQUEST = 'CONFIRM_OTP_REQUEST';
export const CONFIRM_OTP_FAIL = 'CONFIRM_OTP_FAIL';
export const CONFIRM_OTP_SUCCESS = 'CONFIRM_OTP_SUCCESS';

export const SET_PASSWORD_REQUEST = 'SET_PASSWORD_REQUEST';
export const SET_PASSWORD_FAIL = 'SET_PASSWORD_FAIL';
export const SET_PASSWORD_SUCCESS = 'SET_PASSWORD_SUCCESS';

export const ACCEPT_REQUEST = 'ACCEPT_REQUEST';
export const ACCEPT_FAIL = 'ACCEPT_FAIL';
export const ACCEPT_SUCCESS = 'ACCEPT_SUCCESS';

export const TOGGLE_REQUEST = 'TOGGLE_REQUEST';
export const TOGGLE_FAIL = 'TOGGLE_FAIL';
export const TOGGLE_SUCCESS = 'TOGGLE_SUCCESS';

export const OPEN_SERVICE_REQUEST_MODEL = 'OPEN_SERVICE_REQUEST_MODEL';
export const CLOSE_SERVICE_REQUEST_MODEL = 'CLOSE_SERVICE_REQUEST_MODEL';

export const OPEN_PAYMENT_SUCCESS_MODEL = 'OPEN_PAYMENT_SUCCESS_MODEL';
export const CLOSE_PAYMENT_SUCCESS_MODEL = 'CLOSE_PAYMENT_SUCCESS_MODEL';

export const NOTIFICATION_DETAILS = 'NOTIFICATION_DETAILS';

export const GET_ACTIVE_JOB_REQUEST = 'GET_ACTIVE_JOB_REQUEST';
export const GET_ACTIVE_JOB_FAIL = 'GET_ACTIVE_JOB_FAIL';
export const GET_ACTIVE_JOB_SUCCESS = 'GET_ACTIVE_JOB_SUCCESS';
export const GET_ACTIVE_JOB_APPEND_LISTING_SUCCESS =
  'GET_ACTIVE_JOB_APPEND_LISTING_SUCCESS';

export const GET_COMPLETED_JOB_REQUEST = 'GET_COMPLETED_JOB_REQUEST';
export const GET_COMPLETED_JOB_FAIL = 'GET_COMPLETED_JOB_FAIL';
export const GET_COMPLETED_JOB_SUCCESS = 'GET_COMPLETED_JOB_SUCCESS';
export const GET_COMPLETED_JOB_APPEND_LISTING_SUCCESS =
  'GET_COMPLETED_JOB_APPEND_LISTING_SUCCESS';

export const GET_CANCELED_JOB_REQUEST = 'GET_CANCELED_JOB_REQUEST';
export const GET_CANCELED_JOB_FAIL = 'GET_CANCELED_JOB_FAIL';
export const GET_CANCELED_JOB_SUCCESS = 'GET_CANCELED_JOB_SUCCESS';
export const GET_CANCELED_JOB_APPEND_LISTING_SUCCESS =
  'GET_CANCELED_JOB_APPEND_LISTING_SUCCESS';

export const GET_TODAY_JOB_REQUEST = 'GET_TODAY_JOB_REQUEST';
export const GET_TODAY_JOB_FAIL = 'GET_TODAY_JOB_FAIL';
export const GET_TODAY_JOB_SUCCESS = 'GET_TODAY_JOB_SUCCESS';
export const GET_TODAY_JOB_APPEND_LISTING_SUCCESS =
  'GET_TODAY_JOB_APPEND_LISTING_SUCCESS';

export const UPDATE_USER_CURRENT_LOCATION = 'UPDATE_USER_CURRENT_LOCATION';

export const UPDATE_USER_LIVE_LOCATION_REQUEST =
  'UPDATE_USER_LIVE_LOCATION_REQUEST';
export const UPDATE_USER_LIVE_LOCATION_FAIL = 'UPDATE_USER_LIVE_LOCATION_FAIL';
export const UPDATE_USER_LIVE_LOCATION_SUCCESS =
  'UPDATE_USER_LIVE_LOCATION_SUCCESS';

export const GET_NOTIFICATION_REQUEST = 'GET_NOTIFICATION_REQUEST';
export const GET_NOTIFICATION_FAIL = 'GET_NOTIFICATION_FAIL';
export const GET_NOTIFICATION_SUCCESS = 'GET_NOTIFICATION_SUCCESS';

export const UPDATE_NOTIFICATION_REQUEST = 'UPDATE_NOTIFICATION_REQUEST';
export const UPDATE_NOTIFICATION_FAIL = 'UPDATE_NOTIFICATION_FAIL';
export const UPDATE_NOTIFICATION_SUCCESS = 'UPDATE_NOTIFICATION_SUCCESS';

export const UPDATE_ORDER_STATUS_REQUEST = 'UPDATE_ORDER_STATUS_REQUEST';
export const UPDATE_ORDER_STATUS_FAIL = 'UPDATE_ORDER_STATUS_FAIL';
export const UPDATE_ORDER_STATUS_SUCCESS = 'UPDATE_ORDER_STATUS_SUCCESS';

export const CURRENT_SELECTED_ORDER = 'CURRENT_SELECTED_ORDER';

export const SOCKET_REGISTER_REQUEST = 'SOCKET_REGISTER_REQUEST';
export const SOCKET_REGISTER_FAIL = 'SOCKET_REGISTER_FAIL';
export const SOCKET_REGISTER_SUCCESS = 'SOCKET_REGISTER_SUCCESS';

export const GET_ORDER_HISTORY_REQUEST = 'GET_ORDER_HISTORY_REQUEST';
export const GET_ORDER_HISTORY_FAIL = 'GET_ORDER_HISTORY_FAIL';
export const GET_ORDER_HISTORY_SUCCESS = 'GET_ORDER_HISTORY_SUCCESS';
export const GET_ORDER_HISTORY_APPEND_LISTING_SUCCESS =
  'GET_ORDER_HISTORY_APPEND_LISTING_SUCCESS';

export const UPLOAD_CHAT_IMG_REQUEST = 'UPLOAD_CHAT_IMG_REQUEST';
export const UPLOAD_CHAT_IMG_FAIL = 'UPLOAD_CHAT_IMG_FAIL';
export const UPLOAD_CHAT_IMG_SUCCESS = 'UPLOAD_CHAT_IMG_SUCCESS';

export const DELETE_CHAT_REQUEST = 'DELETE_CHAT_REQUEST';
export const DELETE_CHAT_FAIL = 'DELETE_CHAT_FAIL';
export const DELETE_CHAT_SUCCESS = 'DELETE_CHAT_SUCCESS';

export const GET_INBOX_REQUEST = 'GET_INBOX_REQUEST';
export const GET_INBOX_FAIL = 'GET_INBOX_FAIL';
export const GET_INBOX_SUCCESS = 'GET_INBOX_SUCCESS';

export const GET_CHAT_LIST_REQUEST = 'GET_CHAT_LIST_REQUEST';
export const GET_CHAT_LIST_FAIL = 'GET_CHAT_LIST_FAIL';
export const GET_CHAT_LIST_SUCCESS = 'GET_CHAT_LIST_SUCCESS';

export const CREATE_CHAT_ROOM_REQUEST = 'CREATE_CHAT_ROOM_REQUEST';
export const CREATE_CHAT_ROOM_FAIL = 'CREATE_CHAT_ROOM_FAIL';
export const CREATE_CHAT_ROOM_SUCCESS = 'CREATE_CHAT_ROOM_SUCCESS';

export const RATE_USER_REQUEST = 'RATE_USER_REQUEST';
export const RATE_USER_FAIL = 'RATE_USER_FAIL';
export const RATE_USER_SUCCESS = 'RATE_USER_SUCCESS';

export const ADD_BANK_REQUEST = 'ADD_BANK_REQUEST';
export const ADD_BANK_FAIL = 'ADD_BANK_FAIL';
export const ADD_BANK_SUCCESS = 'ADD_BANK_SUCCESS';

export const GET_BANK_REQUEST = 'GET_BANK_REQUEST';
export const GET_BANK_FAIL = 'GET_BANK_FAIL';
export const GET_BANK_SUCCESS = 'GET_BANK_SUCCESS';

export const SET_SLOT_REQUEST = 'SET_SLOT_REQUEST';
export const SET_SLOT_FAIL = 'SET_SLOT_FAIL';
export const SET_SLOT_SUCCESS = 'SET_SLOT_SUCCESS';

export const GET_SLOTS_REQUEST = 'GET_SLOTS_REQUEST';
export const GET_SLOTS_FAIL = 'GET_SLOTS_FAIL';
export const GET_SLOTS_SUCCESS = 'GET_SLOTS_SUCCESS';

export const DELETE_SLOTS_REQUEST = 'DELETE_SLOTS_REQUEST';
export const DELETE_SLOTS_FAIL = 'DELETE_SLOTS_FAIL';
export const DELETE_SLOTS_SUCCESS = 'DELETE_SLOTS_SUCCESS';

export const UPDATE_SLOTS_REQUEST = 'UPDATE_SLOTS_REQUEST';
export const UPDATE_SLOTS_FAIL = 'UPDATE_SLOTS_FAIL';
export const UPDATE_SLOTS_SUCCESS = 'UPDATE_SLOTS_SUCCESS';

export const GET_ALL_SLOTS_REQUEST = 'GET_ALL_SLOTS_REQUEST';
export const GET_ALL_SLOTS_FAIL = 'GET_ALL_SLOTS_FAIL';
export const GET_ALL_SLOTS_SUCCESS = 'GET_ALL_SLOTS_SUCCESS';

export const GET_TODAY_SLOTS_REQUEST = 'GET_TODAY_SLOTS_REQUEST';
export const GET_TODAY_SLOTS_FAIL = 'GET_TODAY_SLOTS_FAIL';
export const GET_TODAY_SLOTS_SUCCESS = 'GET_TODAY_SLOTS_SUCCESS';

export const GET_REPORT_REQUEST = 'GET_REPORT_REQUEST';
export const GET_REPORT_FAIL = 'GET_REPORT_FAIL';
export const GET_REPORT_SUCCESS = 'GET_REPORT_SUCCESS';

export const UPLOAD_DETAILS_REQUEST = 'UPLOAD_DETAILS_REQUEST';
export const UPLOAD_DETAILS_FAIL = 'UPLOAD_DETAILS_FAIL';
export const UPLOAD_DETAILS_SUCCESS = 'UPLOAD_DETAILS_SUCCESS';

export const CHANGE_PASS_REQUEST = 'CHANGE_PASS_REQUEST';
export const CHANGE_PASS_FAIL = 'CHANGE_PASS_FAIL';
export const CHANGE_PASS_SUCCESS = 'CHANGE_PASS_SUCCESS';

export const DELETE_BANK_REQUEST = 'DELETE_BANK_REQUEST';
export const DELETE_BANK_FAIL = 'DELETE_BANK_FAIL';
export const DELETE_BANK_SUCCESS = 'DELETE_BANK_SUCCESS';

export const GET_TERMS_REQUEST = 'GET_TERMS_REQUEST';
export const GET_TERMS_FAIL = 'GET_TERMS_FAIL';
export const GET_TERMS_SUCCESS = 'GET_TERMS_SUCCESS';

export const ADMIN_ID_REQUEST = 'ADMIN_ID_REQUEST';
export const ADMIN_ID_FAIL = 'ADMIN_ID_FAIL';
export const ADMIN_ID_SUCCESS = 'ADMIN_ID_SUCCESS';

export const MUTE_CHAT_REQUEST = 'MUTE_CHAT_REQUEST';
export const MUTE_CHAT_FAIL = 'MUTE_CHAT_FAIL';
export const MUTE_CHAT_SUCCESS = 'MUTE_CHAT_SUCCESS';

export const READ_MESSAGE_REQUEST = 'READ_MESSAGE_REQUEST';
export const READ_MESSAGE_FAIL = 'READ_MESSAGE_FAIL';
export const READ_MESSAGE_SUCCESS = 'READ_MESSAGE_SUCCESS';

export const COMPLETE_JOB_REQUEST = 'COMPLETE_JOB_REQUEST';
export const COMPLETE_JOB_FAIL = 'COMPLETE_JOB_FAIL';
export const COMPLETE_JOB_SUCCESS = 'COMPLETE_JOB_SUCCESS';
